services:
  rabbitmq:
    image: rabbitmq:4.1-alpine
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  
  postgres:
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  bot:
    build:
      context: services/bot
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - RABBIT_HOST=rabbitmq
    env_file:
      - secrets.env
  
  auto-moderator:
    build:
      context: services/auto_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
    env_file:
      - secrets.env
  
  manual-moderator:
    build:
      context: services/manual_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=redis
    env_file:
      - secrets.env
  

volumes:
  rabbitmq-data:
  postgres-data:
  redis-data: