services:
  # Additional
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - media-facade

  rabbitmq:
    image: rabbitmq:4.1-alpine
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  
  postgres:
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - TZ=Europe/Moscow
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Services
  # Bot service
  bot:
    build:
      context: services/bot
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=client-bot-redis
      - TERMS_OF_USE_URL=***REMOVED***
      - PROCESSING_OF_PERSONAL_DATA_URL=***REMOVED***
      # - MESSAGES_TIME_OUT_MINUTES=0 # remove after testing
      # - MAXIMUM_MESSAGES_PER_USER=1000 # remove after testing
      # - MAXIMUM_ATTEMPTS_PER_MESSAGE=1000 # remove after testing
      - MESSAGES_TIME_OUT_MINUTES=1
      - MAXIMUM_MESSAGES_PER_USER=3
      - MAXIMUM_ATTEMPTS_PER_MESSAGE=3
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - postgres

  client-bot-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - client-bot-redis:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec
  
  media-facade:
    build:
      context: services/media_facade
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - RABBIT_HOST=rabbitmq
      - USE_MOCK=1 # Set to 0 in production and set MEDIA_FACADE_API_BASE_URL, MEDIA_FACADE_API_TOKEN
      # - USE_MOCK=0
      # - MEDIA_FACADE_API_BASE_URL=https://light.maergroup.ru/api/vk
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - postgres
  
  # Auto moderator service
  auto-moderator-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - auto-moderator-redis:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  auto-moderator:
    build:
      context: services/auto_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=auto-moderator-redis
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - auto-moderator-redis
  
  # Manual moderator service
  manual-moderator-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - manual-moderator-redis:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  manual-moderator:
    build:
      context: services/manual_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=manual-moderator-redis
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - manual-moderator-redis
  
  # Table moderator service
  table-moderator:
    build:
      context: services/table_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=table-moderator-redis
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - auto-moderator-redis
  
  table-moderator-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - table-moderator-redis:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  # Vision service
  vision-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - vision-redis:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec
  
  # nginx-rtmp: # Remove in production
  #   image: tiangolo/nginx-rtmp:latest-2025-08-18
  #   container_name: nginx_rtmp
  #   restart: always
  #   volumes:
  #     - ./nginx-configs/rtmp-nginx.conf:/etc/nginx/nginx.conf:ro
  
  # vision-mock-video-stream: # Remove in production
  #   build:
  #     context: services/vision
  #     dockerfile: Dockerfile
  #     args:
  #       - SERVICE_NAME=mock_video_stream
  #   restart: always
  #   environment:
  #     - RABBIT_HOST=rabbitmq
  #     - RTMP_URL=rtmp://nginx-rtmp:1935/live
  #     - REDIS_HOST=vision-redis
  #     - DEBUG_MODE=1
  #   env_file:
  #     - secrets.env
  #   depends_on:
  #     - rabbitmq
  #     - vision-redis
  #     - nginx-rtmp
  
  vision-app:
    build:
      context: services/vision
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=app
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=vision-redis
      # - RTMP_URL=rtmp://nginx-rtmp:1935/live # Use mock RTMP server for testing
      # - DEBUG_MODE=1 # Set to 0 in production
      - RTMP_URL=rtmp://h2a.media.maergroup.ru:1940/live/webcamtest2
      - DEBUG_MODE=0
      - ANALYTICS_DELAY_SECONDS=600
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - vision-redis
      # - nginx-rtmp # Use mock RTMP server for testing
  
  vision-frame-matcher:
    build:
      context: services/vision
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=frame_matcher
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=vision-redis
      # - RTMP_URL=rtmp://nginx-rtmp:1935/live # Use mock RTMP server for testing
      # - DEBUG_MODE=1 # Set to 0 in production
      - RTMP_URL=rtmp://h2a.media.maergroup.ru:1940/live/webcamtest2
      - DEBUG_MODE=0
      - ANALYTICS_DELAY_SECONDS=600
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - vision-redis
      # - nginx-rtmp # Use mock RTMP server for testing
  
  vision-frame-processor:
    build:
      context: services/vision
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=frame_processor
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=vision-redis
      # - RTMP_URL=rtmp://nginx-rtmp:1935/live # Use mock RTMP server for testing
      # - DEBUG_MODE=1 # Set to 0 in production
      - RTMP_URL=rtmp://h2a.media.maergroup.ru:1940/live/webcamtest2
      - DEBUG_MODE=0
      - ANALYTICS_DELAY_SECONDS=600
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - vision-redis
      # - nginx-rtmp # Use mock RTMP server for testing

volumes:
  rabbitmq-data:
  postgres-data:
  manual-moderator-redis:
  table-moderator-redis:
  auto-moderator-redis:
  vision-redis:
  client-bot-redis:
