services:
  # Additional
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx_proxy_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx-configs/nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - media-facade
      - cities

  rabbitmq:
    image: rabbitmq:4.1-alpine
    restart: always
    volumes:
      - rabbitmq-data-dev:/var/lib/rabbitmq

  postgres:
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - TZ=Europe/Moscow
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.15.4
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data-dev:/usr/share/elasticsearch/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Services

  # Cities search service
  cities:
    build:
      context: services/cities
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080" # Direct access for testing
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - CITIES_FILE_PATH=/home/cities/app/_cities.csv
      - DEBUG=true
    volumes:
      - ./services/cities:/home/cities/app:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
      - secrets.env

  # Bot service
  bot:
    build:
      context: services/bot
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=client-bot-redis
      - CITIES_SERVICE_URL=http://cities:8080
      - TERMS_OF_USE_URL=***REMOVED***
      - PROCESSING_OF_PERSONAL_DATA_URL=***REMOVED***
      - MESSAGES_TIME_OUT_MINUTES=0 # remove after testing
      - MAXIMUM_MESSAGES_PER_USER=1000 # remove after testing
      - MAXIMUM_ATTEMPTS_PER_MESSAGE=1000 # remove after testing
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - postgres
      - cities

  client-bot-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - client-bot-redis-dev:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  media-facade:
    build:
      context: services/media_facade
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8000" # Direct access for testing
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - RABBIT_HOST=rabbitmq
      - USE_MOCK=1 # Set to 0 in production and set MEDIA_FACADE_API_BASE_URL, MEDIA_FACADE_API_TOKEN
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - postgres

  # Auto moderator service
  auto-moderator-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - auto-moderator-redis-dev:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  auto-moderator:
    build:
      context: services/auto_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=auto-moderator-redis
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - auto-moderator-redis

  # Manual moderator service
  manual-moderator-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - manual-moderator-redis-dev:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  manual-moderator:
    build:
      context: services/manual_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=manual-moderator-redis
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - manual-moderator-redis

  # Table moderator service
  table-moderator:
    build:
      context: services/table_moderator
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=table-moderator-redis
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - table-moderator-redis

  table-moderator-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - table-moderator-redis-dev:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  # Vision service
  vision-redis:
    image: redis:8.2.0-alpine
    restart: always
    volumes:
      - vision-redis-dev:/data
    command: >
      redis-server
      --save 60 1
      --save 300 10
      --appendonly yes
      --appendfsync everysec

  vision-app:
    build:
      context: services/vision
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=app
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=vision-redis
      - RTMP_URL=rtmp://h2a.media.maergroup.ru:1940/live/webcamtest3
      - DEBUG_MODE=0
      - ANALYTICS_DELAY_SECONDS=600
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - vision-redis

  vision-frame-matcher:
    build:
      context: services/vision
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=frame_matcher
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=vision-redis
      - RTMP_URL=rtmp://h2a.media.maergroup.ru:1940/live/webcamtest3
      - DEBUG_MODE=0
      - ANALYTICS_DELAY_SECONDS=600
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - vision-redis

  vision-frame-processor:
    build:
      context: services/vision
      dockerfile: Dockerfile
      args:
        - SERVICE_NAME=frame_processor
    restart: always
    environment:
      - RABBIT_HOST=rabbitmq
      - REDIS_HOST=vision-redis
      - RTMP_URL=rtmp://h2a.media.maergroup.ru:1940/live/webcamtest3
      - DEBUG_MODE=0
      - ANALYTICS_DELAY_SECONDS=600
    env_file:
      - secrets.env
    depends_on:
      - rabbitmq
      - vision-redis
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
volumes:
  rabbitmq-data-dev:
  postgres-data-dev:
  elasticsearch-data-dev:
  manual-moderator-redis-dev:
  table-moderator-redis-dev:
  auto-moderator-redis-dev:
  vision-redis-dev:
  client-bot-redis-dev:
