[project]
name = "vision"
version = "0.1.0"
description = ""
authors = [
    {name = "ycalk",email = "alosev752@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "facade-message-bot-shared-models[messaging] (>=0.12.0,<0.13.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "redis (>=6.4.0,<7.0.0)",
    "paddleocr (>=3.1.1,<4.0.0)",
    "paddlepaddle (>=3.1.0,<4.0.0)",
    "setuptools (>=80.9.0,<81.0.0)",
    "thefuzz (>=0.22.1,<0.23.0)",
    "sentry-sdk (>=2.35.1,<3.0.0)",
]

[tool.poetry]
packages = [{include = "vision", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
app = "vision:run_app"
mock_video_stream = "vision:run_mock_video_stream"
frame_matcher = "vision:run_frame_matcher"
frame_processor = "vision:run_frame_processor"