name: Deploy

on:
  push:
    branches: [stage]

jobs:
  test-bot:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/bot
    env:
      BOT_TOKEN: f9LHodD0cOK9FCQR5-mTNoXfQT4u7iEBPK2j3PoWO77zjySLFoWo9ial6RbOxydqoPHcNyTQE6orS3FQFVYp
      NAME_API_KEY: 60903c28-a108-43ea-95aa-7b50ed3d561f
      POSTGRES_USER: some user
      POSTGRES_PASSWORD: some password
      POSTGRES_DB: some database
      IS_TESTING: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir poetry==2.1.3
          poetry install --with dev

      - name: Run tests
        run: |
          poetry run pytest --disable-warnings -v

  copy:
    needs: test-bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive code for deploy
        run: |
          zip -r deploy.zip . -x '*.git*' '*.github/*'

      - name: Create secrets.env file
        run: |
          echo "SENTRY_DSN=http://52cb9f7304933df00e6f4dc2de598ba7@82.202.129.230:9000/4" >> secrets.env
          echo "BOT_TOKEN=f9LHodD0cOK9FCQR5-mTNoXfQT4u7iEBPK2j3PoWO77zjySLFoWo9ial6RbOxydqoPHcNyTQE6orS3FQFVYp" >> secrets.env
          echo "NAME_API_KEY=60903c28-a108-43ea-95aa-7b50ed3d561f" >> secrets.env
          echo "MISTRAL_API_KEY=f8ZUgmWSbWf0jP0nuhWUmppR6slkTTYn" >> secrets.env
          echo "TELEGRAM_BOT_TOKEN=8208310640:AAHX-vf-FsEfvHeeEIjvJFI0wDNyOO5XBkY" >> secrets.env
          echo "MAIN_ADMIN_ID=75178947" >> secrets.env
          echo "MEDIA_FACADE_API_TOKEN=c2776116-3537-45d4-81df-926e49974f86" >> secrets.env
          echo "SECRET_KEY=0d16efe6-8770-4ee6-a78d-f9cfae4a0fed" >> secrets.env
          echo "START_MESSAGE_IMAGE_TOKEN=uzz8EEFL1p4bKp3yXOov39UieRyxG2u5jFajHbjNbqtid+UEKpizOiRdYZLca73nfH8oYnwxLqqVVt5oeJA3t4GkJMU5TFnnKXZ4qcOz3DZob+NFxv7BFbsOfzL4Rh9C3fPRwRAnalxO45uS0xrmxmqWH92fK5ufbjNjpA/QyPg\u003d" >> secrets.env
          echo "GOOGLE_SHEET_ID=1Ef6OUBgWFuJcykGuJWt6zRIjad9aVNbZ8Hvu4ro9pxM" >> secrets.env
          echo "GOOGLE_ACCOUNT_CREDENTIALS=$(echo 'eyJ0eXBlIjoic2VydmljZV9hY2NvdW50IiwicHJvamVjdF9pZCI6ImJudy1iYXphIiwicHJpdmF0ZV9rZXlfaWQiOiJmMzY1ODMzMDhkOGJhMmFmYThmZjQ4NGU4ZGQ2MDcyNzNkZDkzOWQ1IiwicHJpdmF0ZV9rZXkiOiItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ245dzk1SXF3dk5KNkVcbnI5Um5ZUnlpbjlGSEZvQnV6N0RqZWQwNU4xSjhqQmpydXA0NnN5UmtJdHJITGtHajRwQzh6K2lURldSOGY4OFRcbk5pUmZZWTJycVJhUEQ1emVpdEtKOW9EU0QvalArSVA4UTRlVEZUUnFWL1NPT3JnbGNzaGkrakZ0MmdKelBSNEFcbjVJd25EdzdyVGg0bE5rWXBPMDlUY0dXUzlWcVBCeHEzZndxZ29keCtka0FSaXF6ZjBydWJvMlBQdjF5blFRWU9cbk5wM2hsRWJ3RHNoM2ZacDE3TmRkTFdqNGl2c1pEcU9sTVAzaVgwZzA4SnBKWjlBTVN4d214YUxlT1dJdTdQV0RcbmtnS1gwZzlQb1BZQ0N2TTJqSGZHSTVWVXJxektuaElLTlpORU52SEZqL3JQdG1YRmMxN2hVb3FSekpCZjBlYzdcbitnNkZsQndMQWdNQkFBRUNnZ0VBTlhWV0tPVkdyUTJQeUVaWUVZRWdob2ZjS1VaNW9Rc2NUd0laelZ5VXRjdzNcbklFdTRrWkV6cTJWR2dXOXc5OUtqNDF3K3R4VnZjb3FSSXhtdjBPV3hHK29Jb29iREZEZFYxQkF2SnV4cmNmRzBcblBFVlg4SkdtcVpRTjQzaS81RGRZbk52cGdIK0xHUmRpSmNHWDg5U0FtSmEzMUhzbU1IaE9nbzE2M3ArVmI0QzdcbndlUVBLbXZ2TkIvUytTNllZYmx0bzdWTjMxTk5vNUNSRENDdnQrMkxFaFF4WFcvUkdnMHNiU3hOc3VoMk5VTTlcbnBrWmZiRHE0R3lzSlpWY3dmbjlGeWNqbVRsd3V4aU5ycjhBOVVDSWd4dUFscXRMbm1UVWlqSDY2V2lJTHBJM25cbmJkQzJBMGtXcEVyRnNxRU9PUG1LTngyd0hVZU84Sko3dlc4Yk9JZk4vUUtCZ1FEcjNOR3hqY043U09iYjhmdFhcbnpOdFhMdERvMlJSWUlQeVpwRGVFNjJOMHdKbVVuKzBuZUZXTDB4b3hVdnJ3NmxJR0l6QWpudzA2K0NsOEdhTnRcbnk0cXFTaWw2TU9EREdQZ0RFMDhzNm50TTVCdWlvbENpVXhnT2MzV20zeWswV2tnWHluZEdtaENpOWY2TURCOTBcbmhXSGhNcXVyYllYeFErNFd1bUtUVngzd2RRS0JnUUMyVGptbDVkc0hFWE85Q3RlSTNPcnJGQnN5cVNMZ3YvTGNcbldXSEIzcTJnZ0lmN0xOcTgvTGRhVmlnZXdxRXp6M2VHUmthUlk4WnlSWVZMelNVZDZlS1VRQi90d0J5cjVTQW9cbktZZ2NIVW9WRmY4QjdmUmdDMk9HeWcwUm9TcUJJNmNKTWUyZFdzdlRKRUtidS9DNDgrMndFVjI5Tm9GcmF6c1VcblBKc3BSbGhLZndLQmdBMks4Vk5qazJ6Wnc3K3ZSa0pGVmZiTWpseEFVcVc0eHlnL1FKeldNekM1K2xlSlUwR25cbjdDbUtKbi9jaHVJY1lqZE4vKzZickZQTmVmeFJNSXdXV3REcVR6VmY1eGZzc0JqbEcrKzFTdjBnUCtIM3RlK01cbkc5NkFqS25YT0hOMEY1MmVGM2tyVVhjNTdySzE0M3g2U0NONUdGaFFncGRXMGkzbDU5RVQrSGtkQW9HQUQ3U2hcbmhzZE1uVWxGblUybnorU29ZR1ExQzZKQ25QWXNhQXRUUHE1K2FzdG42NTJyb29ockMxOU15WW1lOWFXeitGOXBcbmlQRDlrYTZua3lZelFtWjUzS2ZCbUd2cWpHeUszcXJsVFBiQkFSd0tBaEtMOFJKS0dyeWhiNWxnM2d0Q1FxcUlcbmUvdnNmMTRxVnR4VUdycjVDU2dWMlUwdXpTQkowSzUvOTRoVjV1VUNnWUJJSkZuVVN0d3lja2c4KzhjSjJVWG9cbjdidHdLOUJmd0dGSU5uNElsN0daWjBmRTRlckNlVXlpVW1lMjYycDlJdTFhRWtkaGJIN01wSk1BRHVBL0dQUnlcbmM0dUhjVVBjY3Q0cVZvdlRKRUZhSURzanFybENrVzJvOHE2NEoyZ2NMTCtsb09takR6SjJOTUFZbUxMVkF2WFNcbkdJd05zY1pVQnA4REdKVzVDVUhSbkE9PVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwiY2xpZW50X2VtYWlsIjoic3RhZ2UtZmFjYWRlQGJudy1iYXphLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwiY2xpZW50X2lkIjoiMTE3Mzc0ODQwMTcxNDMyNzkzNDI1IiwiYXV0aF91cmkiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsInRva2VuX3VyaSI6Imh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwiY2xpZW50X3g1MDlfY2VydF91cmwiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3N0YWdlLWZhY2FkZSU0MGJudy1iYXphLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwidW5pdmVyc2VfZG9tYWluIjoiZ29vZ2xlYXBpcy5jb20ifQ==' | base64 -d)" >> secrets.env
      - name: Transfer files to server
        uses: appleboy/scp-action@v1
        with:
          host: 83.222.26.189
          username: root
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACAtnFp+Y2e0VUmmNqzrkmDv25WbZrQO0oL0KLVUDa9+7wAAAJhPCWjrTwlo
            6wAAAAtzc2gtZWQyNTUxOQAAACAtnFp+Y2e0VUmmNqzrkmDv25WbZrQO0oL0KLVUDa9+7w
            AAAECpplG++laSSRORFuERvo7Miun9VFaeHJz3Y97hoe18oS2cWn5jZ7RVSaY2rOuSYO/b
            lZtmtA7SgvQotVQNr37vAAAAD3Jvb3RAa3JlZ3pkZXFpdwECAwQFBg==
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          source: "deploy.zip,secrets.env"
          target: "/home/root/facade-message-bot/deploy/"

  build:
    runs-on: ubuntu-latest
    needs: copy
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 83.222.26.189
          username: root
          key: |
            key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACAtnFp+Y2e0VUmmNqzrkmDv25WbZrQO0oL0KLVUDa9+7wAAAJhPCWjrTwlo
            6wAAAAtzc2gtZWQyNTUxOQAAACAtnFp+Y2e0VUmmNqzrkmDv25WbZrQO0oL0KLVUDa9+7w
            AAAECpplG++laSSRORFuERvo7Miun9VFaeHJz3Y97hoe18oS2cWn5jZ7RVSaY2rOuSYO/b
            lZtmtA7SgvQotVQNr37vAAAAD3Jvb3RAa3JlZ3pkZXFpdwECAwQFBg==
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            cd /home/root/facade-message-bot/deploy/
            unzip -o deploy.zip
            sudo docker compose -f docker-compose.dev.yaml build
            sudo docker compose -f docker-compose.dev.yaml down
            sudo docker compose -f docker-compose.dev.yaml up -d --remove-orphans
            sudo docker image prune -f
            rm deploy.zip
